name: deploy_mate
description: CI/CD tool for your flutter projects
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  interact: ^2.2.0
  yaml: ^3.1.3
  dio: ^5.7.0


dev_dependencies:
  test: ^1.25.14