name: deploy_mate
description: CI/CD tool for your flutter projects
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  interact: ^2.2.0
  yaml: ^3.1.3
  yaml_writer: ^2.0.0
  path: ^1.9.0
  dio: ^5.7.0
  http: ^1.2.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.14